# Generated by Django 4.1.4 on 2022-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddGameModel',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=500)),
                ('game_platform', models.CharField(max_length=500)),
                ('game_image', models.ImageField(null=True, upload_to='images/')),
                ('game_url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'Game_details',
            },
        ),
    ]
