# Generated by Django 4.1.4 on 2022-12-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestions',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Game_questions',
            },
        ),
    ]
