# Generated by Django 4.1.4 on 2022-12-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_addquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquestions',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addquestions',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addquestions',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addquestions',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
