# Generated by Django 4.1.4 on 2022-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_addquestions_option1_addquestions_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquestions',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
