# Generated by Django 4.1.4 on 2022-12-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquestions',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.addgamemodel'),
        ),
    ]
