# Generated by Django 4.1.4 on 2022-12-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_addquestions_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgamemodel',
            name='game_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
