# Generated by Django 4.1.4 on 2022-12-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_join_date', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('sentiment', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
    ]
