# Generated by Django 4.1.4 on 2022-12-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_prifile',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
