# Generated by Django 4.1.4 on 2022-12-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_analysis'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analysis',
            table='result_analysis',
        ),
    ]
